recipes:
  recipe1:
    inputs:
      - SUGAR
      - REDSTONE
    output:
      POTION:1:
        display-name: "Strong Speed Potion"
        lore:
          - "This potion will increase your speed."
        effects:
          speed:
            duration: 1200
            amplifier: 1
            color: "#FF7F28"
  recipe2:
    inputs:
      - SPIDER_EYE
      - GUNPOWDER
    output:
      SPLASH_POTION:1:
        display-name: "Poison Splash Potion"
        lore:
          - "This potion will poison any players hit."
        effects:
          poison:
            duration: 160
            amplifier: 0
            color: "#4C2C1D"