recipes:
  recipe1:
    input:
      - sugar
      - spider_eye
    output:
      item1:
        material: SPLASH_POTION
        amount: 2
        lore: This is a custom potion
      item2:
        material: TIPPED_ARROW
        amount: 1
  recipe2:
    input:
      - rabbit_foot
      - nether_wart
    output:
      item1:
        material: LINGERING_POTION
        amount: 1
        lore: This is another custom potion
