name: PotionBrewing
main: pbrew.potionbrewing.Potionbrewing
api-version: 1.19
version: 1.0
author: cake5diamond
description: A plugin that allows players to mix ingredients in a brewing stand to create potions
commands:
  pbreload:
    description: Reloads the plugin's configuration file
    permission: pbrew.reload

permissions:
  pbrew.reload:
    description: Allows access to the pbreload command
    default: op
  pbrew.potions:
    description: Allows access to the shift + right click on a brewing stand.
    default: op